In [35]:
import numpy as np
import pandas as pd

In [36]:
class Perceptron():
    def __init__(self, lr: float = 0.01, max_iter: int = 1000, random_state=None):
        self.weights = None
        self.bias = None
        self.lr = lr
        self.max_iter = max_iter
        self.coef_ = None
        self.intercept_ = None
        if random_state is not None:
            np.random.seed(random_state)

    def loss_function(self, y_true, y_pred):
        """mse loss function"""
        return np.mean((y_pred - y_true) ** 2)

    def fit(self, X, y):
        """training through gradient descent"""
        X = np.array(X)
        y = np.array(y).reshape(-1, 1)
        
        n_samples, n_features = X.shape
        
        self.weights = np.random.randn(n_features, 1) * 0.01
        self.bias = 0.0
        
        for epoch in range(self.max_iter):
            y_pred = np.dot(X, self.weights) + self.bias
            
            error = y_pred - y
            dw = (1 / n_samples) * np.dot(X.T, error)  #  1/n_samples for mse normalization
            db = (1 / n_samples) * np.sum(error)       # np.sum() to get scalar
            
            self.weights -= self.lr * dw
            self.bias -= self.lr * db
            
        self.coef_ = self.weights.flatten() # flatten() convers negative to a whole positive number
        self.intercept_ = self.bias
        
        return self

    def predict(self, X):
        """Predict using the trained model"""
        X = np.array(X)
        y_pred = np.dot(X, self.weights) + self.bias
        return y_pred.flatten()

In [37]:
df = pd.read_csv('salary.csv')

In [38]:
df.head()

   cgpa  resume_score  salary_in_pkr
0  6.82          7.59      120000.00
1  9.21          5.30      120000.00
2  8.30          5.61      120000.00
3  7.75          8.64      120000.00
4  5.92          7.44      103233.05

In [39]:
x, y = df.iloc[:, :-1], df['salary_in_pkr']

In [40]:
x.head()

   cgpa  resume_score
0  6.82          7.59
1  9.21          5.30
2  8.30          5.61
3  7.75          8.64
4  5.92          7.44

In [41]:
y.head()

0    120000.00
1    120000.00
2    120000.00
3    120000.00
4    103233.05
Name: salary_in_pkr, dtype: float64

In [42]:
pr = Perceptron()

In [43]:
x, y = np.array(x), np.array(y)

In [44]:
pr.fit(x, y)

In [45]:
print(pr.coef_, pr.intercept_)

[7972.75335947 7389.06721115] -1376.8343013754918

In [46]:
result = pr.predict(x)
print('Actual_label vs Predicted_label:\n')

total = 0
for actual, predicted in zip(y, result):
    if actual == predicted:
        total += 1
        print(f'Correct: {actual:.0f} = {predicted:.0f}')
    else:
        print(f'Wrong: {actual:.0f} != {predicted:.0f}')
print(f"\nAccuracy: {total/len(result)}")

Actual_label vs Predicted_label:

Wrong: 120000 != 109080
Wrong: 120000 != 111214
Wrong: 120000 != 106250
Wrong: 120000 != 124254
Wrong: 103233 != 100797
Wrong: 64244 != 82693
Wrong: 63884 != 82232
Wrong: 120000 != 126010
Wrong: 92771 != 97215
Wrong: 120000 != 105452
Wrong: 82605 != 94632
Wrong: 120000 != 130251
Wrong: 120000 != 124524
Wrong: 86258 != 91029
Wrong: 113257 != 104845
Wrong: 84094 != 90516
Wrong: 95408 != 97162
Wrong: 120000 != 117201
Wrong: 120000 != 111215
Wrong: 120000 != 112650
Wrong: 120000 != 117337
Wrong: 97258 != 99130
Wrong: 75919 != 89744
Wrong: 101206 != 100492
Wrong: 105084 != 100338
Wrong: 120000 != 110516
Wrong: 120000 != 113389
Wrong: 116829 != 106168
Wrong: 120000 != 123867
Wrong: 92081 != 97868
Wrong: 120000 != 121469
Wrong: 97503 != 98171
Wrong: 85529 != 96880
Wrong: 120000 != 123474
Wrong: 120000 != 115018
Wrong: 120000 != 125870
Wrong: 94252 != 95759
Wrong: 68969 != 81143
Wrong: 120000 != 119359
Wrong: 95403 != 97120
Wrong: 119322 != 109877
Wrong: 120000 != 122525
Wrong: 110735 != 106115
Wrong: 120000 != 118424
Wrong: 74342 != 86190
Wrong: 120000 != 127287
Wrong: 105082 != 100505
Wrong: 120000 != 123691
Wrong: 120000 != 124495
Wrong: 120000 != 109290
Wrong: 120000 != 118127
Wrong: 120000 != 114483
Wrong: 120000 != 134091
Wrong: 120000 != 116320
Wrong: 107845 != 102160
Wrong: 120000 != 124592
Wrong: 116582 != 108613
Wrong: 112739 != 104806
Wrong: 98079 != 96021
Wrong: 87490 != 90934
Wrong: 120000 != 108746
Wrong: 120000 != 116218
Wrong: 120000 != 108848
Wrong: 112520 != 104754
Wrong: 120000 != 113138
Wrong: 120000 != 117617
Wrong: 101801 != 102972
Wrong: 120000 != 125039
Wrong: 69669 != 90623
Wrong: 120000 != 118765
Wrong: 120000 != 127334
Wrong: 118269 != 108359
Wrong: 107347 != 103680
Wrong: 120000 != 131872
Wrong: 120000 != 116093
Wrong: 120000 != 116515
Wrong: 120000 != 126885
Wrong: 100364 != 99416
Wrong: 116740 != 110370
Wrong: 119235 != 105205
Wrong: 120000 != 132722
Wrong: 117914 != 108056
Wrong: 92065 != 99517
Wrong: 70115 != 82170
Wrong: 111282 != 105086
Wrong: 85020 != 89087
Wrong: 120000 != 115406
Wrong: 120000 != 114741
Wrong: 120000 != 115195
Wrong: 120000 != 110718
Wrong: 61311 != 82162
Wrong: 110231 != 101843
Wrong: 120000 != 127305
Wrong: 116323 != 106648
Wrong: 117898 != 106491
Wrong: 120000 != 109366
Wrong: 120000 != 117786
Wrong: 92118 != 97904
Wrong: 84813 != 97008
Wrong: 72449 != 83389
Wrong: 60101 != 79804
Wrong: 120000 != 114292
Wrong: 117507 != 103984
Wrong: 120000 != 113397
Wrong: 120000 != 129212
Wrong: 120000 != 115058
Wrong: 120000 != 106434
Wrong: 120000 != 111998
Wrong: 117729 != 108952
Wrong: 79938 != 87969
Wrong: 104719 != 100083
Wrong: 76377 != 84922
Wrong: 117204 != 108649
Wrong: 120000 != 133185
Wrong: 120000 != 123522
Wrong: 120000 != 127130
Wrong: 120000 != 116178
Wrong: 67043 != 88601
Wrong: 120000 != 111444
Wrong: 111851 != 102605
Wrong: 120000 != 120544
Wrong: 120000 != 128518
Wrong: 120000 != 107764
Wrong: 71205 != 89380
Wrong: 120000 != 113675
Wrong: 120000 != 113716
Wrong: 120000 != 121090
Wrong: 120000 != 124145
Wrong: 68473 != 90164
Wrong: 105526 != 101575
Wrong: 99395 != 101796
Wrong: 119477 != 107530
Wrong: 64429 != 81645
Wrong: 80084 != 91924
Wrong: 120000 != 109713
Wrong: 73692 != 89155
Wrong: 120000 != 120366
Wrong: 120000 != 121771
Wrong: 104410 != 103663
Wrong: 120000 != 112222
Wrong: 120000 != 123873
Wrong: 96788 != 99916
Wrong: 99633 != 98886
Wrong: 96841 != 100334
Wrong: 95818 != 98741
Wrong: 86959 != 97106
Wrong: 120000 != 116592
Wrong: 92505 != 95203
Wrong: 75966 != 90269
Wrong: 113401 != 105374
Wrong: 120000 != 122488
Wrong: 120000 != 111118
Wrong: 107029 != 102023
Wrong: 102720 != 98351
Wrong: 120000 != 111887
Wrong: 107640 != 104695
Wrong: 102041 != 100193
Wrong: 120000 != 120137
Wrong: 120000 != 113551
Wrong: 120000 != 118726
Wrong: 112439 != 101157
Wrong: 120000 != 117611
Wrong: 120000 != 111996
Wrong: 120000 != 111466
Wrong: 120000 != 108761
Wrong: 120000 != 116550
Wrong: 120000 != 117006
Wrong: 117653 != 110842
Wrong: 59806 != 84482
Wrong: 101330 != 98892
Wrong: 104924 != 102648
Wrong: 48231 != 78291
Wrong: 92951 != 96999
Wrong: 106421 != 105473
Wrong: 112828 != 100646
Wrong: 89726 != 92636
Wrong: 120000 != 125658
Wrong: 89898 != 90711
Wrong: 120000 != 132903
Wrong: 75969 != 90331
Wrong: 92784 != 92078
Wrong: 106528 != 102095
Wrong: 120000 != 126815
Wrong: 120000 != 132831
Wrong: 113154 != 108061
Wrong: 120000 != 123365
Wrong: 120000 != 112735
Wrong: 114268 != 100947
Wrong: 120000 != 117508
Wrong: 120000 != 109720
Wrong: 116889 != 110398
Wrong: 120000 != 119356
Wrong: 120000 != 118259
Wrong: 120000 != 121675
Wrong: 99296 != 98722
Wrong: 120000 != 117076
Wrong: 120000 != 127297
Wrong: 120000 != 119799
Wrong: 120000 != 129308
Wrong: 120000 != 125874

Accuracy: 0.0